# which branch to trigger the workflow on
name: Deploy Node.js App to ExCloud Server
on:
  push:
    branches:
      - main

# steps 
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy on ExCloud Server
        uses: appleboy/ssh-action@v1.2.5
        with: 
          host: 210.79.129.202
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            cd /home/ubuntu/DevOps
            git pull 
            npm install
            pm2 delete index || true
            pm2 start index.js --name index

